DROP TABLE IF EXISTS WORKS_ON;
DROP TABLE IF EXISTS DEPT_LOCATIONS;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
    Dname VARCHAR(30),
    Dnumber INTEGER,
    Mgrssn VARCHAR(30),
    Mgr_start_date DATE,
    PRIMARY KEY(Dnumber)
);

CREATE TABLE EMPLOYEE (
    Fname VARCHAR(30),
    Minit CHAR(1),
    Lname VARCHAR(30),
    Ssn VARCHAR(30),
    Bdate DATE,
    Address VARCHAR(256),
    Sex CHAR(1),
    Salary INTEGER,
    Super_ssn VARCHAR(9),
    Dno INTEGER,
    PRIMARY KEY (Ssn),
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE PROJECT (
    Pname VARCHAR(30),
    Pnumber INTEGER,
    Plocation VARCHAR(30),
    Dnum INTEGER,
    PRIMARY KEY (Pnumber),
    FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE WORKS_ON(
    Essn VARCHAR(9),
    Pno INTEGER,
    Hours INTEGER,
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
    FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
);

CREATE TABLE DEPT_LOCATIONS(
    Dnumber INTEGER,
    Dlocation VARCHAR(30),
    PRIMARY KEY (Dnumber, Dlocation),
    FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
);
